### ISSUE TITLE
Its already cleaning from bigpools?

### ISSUE THREAD

**Issue by obseletecode72** [TheCruZ/kdmapper#117]
i saw that i need to clean the driver from the big pools, the code that i am trying here for some reason it is giving bsod (with others mappers doesnt happens that), but i realized that have a option "--free" does that argument cleans it from the big pools?

**Comment by TheCruZ** [comment]
--free is to release the allocated memory not to clear bigpools, and about your crash I can't tell you too much but probably you should know from the readme that parameters of driver entry are null

PD: kdmapper will never clear bigpools since is a design of the driver that you create and kdmapper just gives you the methods for the allocation and you can even use other methods like mdl allocation or independent page allocation
