### ISSUE TITLE
kdstinker is that still a thing?

### ISSUE THREAD

**Issue by evo15** [TheCruZ/kdmapper#124]
https://www.unknowncheats.me/forum/c-and-c-/424102-kdstinker-dump-drivers-mapped-using-kdmapper.html

People were using this to dump from intel driver. Did you fix that or is that still a thing??

**Comment by TheCruZ** [comment]
Kdstinker was a tool that hook intel driver IOCTLs, in general is pretty straightforward to bypass, in any case no, kdmapper is not intended to bypass kdstinker

if you don't want to map your driver if kdstinker exists verify that MAJOR from intel driver points to intel driver area or add a extra function to unhook major (since you know correct offset of the dispatch)
