### ISSUE TITLE
[!!] Crash at addr 0x00007FF6DBA0C9A5 by 0xc0000005

### ISSUE THREAD

**Issue by DavidTheTech** [TheCruZ/kdmapper#29]
keep getting crash when launching

[<] Loading vulnerable driver, Name: vplfLaemxNtg
[+] NtLoadDriver Status 0x0
[+] PiDDBLock Ptr 0xfffff8064012323c
[+] PiDDBCacheTable Ptr 0xfffff80640123378
[+] PiDDBLock Locked
[+] PiDDBCacheTable result -> TimeStamp: 5284eac3
[+] Found Table Entry = 0xFFFF8A026C2AA4D0
[+] PiDDBCacheTable Cleaned
[+] g_KernelHashBucketList Found 0xFFFFF80640EBC080
[+] g_HashCacheLock Locked
[+] Found In g_KernelHashBucketList: vplfLaemxNtg
[+] g_KernelHashBucketList Cleaned
[+] MmUnloadedDrivers Cleaned: vplfLaemxNtg
[+] Image base has been allocated at 0xFFFFD08FD7FE0000
[+] Skipped 0x1000 bytes of PE Header
[!!] Crash at addr 0x00007FF6DBA0C9A5 by 0xc0000005
[<] Unloading vulnerable driver
[+] NtUnloadDriver Status 0x0
[+] Vul driver data destroyed before unlink

**Comment by TheCruZ** [comment]
Is your driver packed? Looks like the crash occurs more or less when resolving imports/relocating memory, if you can provide the packed driver in some way for further analysis of the PE Header and debug what is wrong but in any case packed drivers may not be supported because some use exception catch to unpack/load the driver later and kdmapper will not support exceptions at kernel
