### ISSUE TITLE
Bypass custom entry point

### ISSUE THREAD

**Issue by Jerem584** [TheCruZ/kdmapper#37]
Hey,

As you know setting a custom entry point remove the "crtstartup" < at least in usermode

But here's two things that should work:

1- driver export (would work fine)
2- trace crt startup to get the real main and so skip the check and so the bsod

Here's just theory but I would like to know what you guys think,

Ill maybe write a small test to skip crt startup and make a PR once I got it to work

Thanks :)

**Comment by TheCruZ** [comment]
Basically, you want to add a feature to directly reverse real entry point and call it from kdmapper, true?

I'm not sure if people will want this because it will be like having unnecessary bytes at kernel that will never be used since we will not use that startup never

if you give me a proof concept with a small code, I can implement it as param but while that I don't  see a real good reason (apart from the people that don't know what means set custom entry point) to add this to the project, if  you want to do it, you are always open to do a pull request

**Comment by Jerem584** [comment]
> Basically, you want to add a feature to directly reverse real entry point and call it from kdmapper, true?
> 
> I'm not sure if people will want this because it will be like having unnecessary bytes at kernel that will never be used since we will not use that startup never
> 
> if you give me a proof concept with a small code, I can implement it as param but while that I don't see a real good reason (apart from the people that don't know what means set custom entry point) to add this to the project, if you want to do it, you are always open to do a pull request

well i guess it could be useful somehow to not have any requirement.
guess we can clear thoses useless bytes and the security cookie ofc
Ill write one when i have time of course
