### ISSUE TITLE
BSOD WIN11 21H2 22000.376

### ISSUE THREAD

**Issue by Jorgi3** [TheCruZ/kdmapper#47]
loading helloworld.sys causing BSOD

**Comment by S0PEX** [comment]
Would you mind posting the BSOD dump?
I just tested the example driver with the latest version of kdmapper and can't reproduce the error.

**Comment by TheCruZ** [comment]
I'm not able to reproduce the issue

**Comment by xxTree** [comment]
BSOD WIN10 21H2 19044.1415
[010822-6750-01.txt](https://github.com/TheCruZ/kdmapper/files/7832431/010822-6750-01.txt)
txt --> dmp

**Comment by TheCruZ** [comment]
> 

Sorry but this BSOD isn't related to this issue since the OP is speaking about Windows 11 BSOD, also your BSOD is Bug Check 0x109 CRITICAL_STRUCTURE_CORRUPTION which probably related to your loaded driver and not to kdmapper since this is so specific BSOD

I will close the issue since I can not reproduce it

**Comment by winsoning** [comment]
Open Kernel Isolation   load Helloworld.sys  bsod
