### ISSUE TITLE
Malware Detected

### ISSUE THREAD

**Issue by Knabora** [TheCruZ/kdmapper#60]
I am trying to implement this in my project but when the kdmapper.exe is always detecting a false malware positive. I know it isn't but that's not what others think as on virustotal it's full of malware.

**Comment by TheCruZ** [comment]
The problem is that at the end you are loading untrusted stuff on kernel apart that people can use this for different things then antivirus must detect it, you can remove basic detections with code modifications, mutations and packing etc but some antivirus already implement the protocol to detect when it drops the intel driver, load it and call IOCTL on bad ways etc

We can't do nothing about this
