### ISSUE TITLE
Two problem when load

### ISSUE THREAD

**Issue by luciouskami** [TheCruZ/kdmapper#81]
When load my driver, DriverObject is null.
PsGetCurrentProcess returns "kdmapper.exe"'s _EPROCESS,current is PsInitialSystemProcess.
example:
[code](https://github.com/processhacker/processhacker/blob/2b70d0a678dc06c330545085daf1f8375487b328/KProcessHacker/main.c#L374)

**Comment by TheCruZ** [comment]
You are in kdmapper process and have null driver object because kdmapper call entrypoint of your driver after manually map it
https://github.com/TheCruZ/kdmapper/blob/3a21e3a5a8955633d6b8fb159ae605420e44802e/kdmapper/kdmapper.cpp#L148
you can pass whatever you want and about the process just create a thread or hijack something at kernel to be in different process

**Comment by luciouskami** [comment]
ok thank you, i'll try two fix it
